version: '3'

services:

  api:
    container_name: luby_cash_api
    build: .
    image: luby_cash_api
    volumes: 
      - .:/usr/app/api
      - ./node_modules:/usr/app/api/node_modules
    ports: 
      - "3333:3333"
    command: npm run dev
    depends_on:
      - db
    links:
      - db

  db:
    container_name: api_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: luby_cash
      POSTGRES_USER: luby_cash
      POSTGRES_DB: luby_cash_db

